### ISSUE TITLE
Drop support for older PHP versions

### ISSUE THREAD

**Issue by oliverklee** [sabberworm/PHP-CSS-Parser#207]
I propose this library drops support for older PHP versions so it can use newer PHP features.

According to https://www.php.net/supported-versions.php, PHP 7.2 recently reached its end of life. So I propose to drop support for all PHP versions < 7.2.

(We then can use Rector to upgrade the code accordingly.)

What do you think?

**Comment by oliverklee** [comment]
And in https://github.com/MyIntervals/emogrifier, we'd like to use this library. Our next major release will still support PHP 7.2, so PHP-CSS-Parser still supporting PHP 7.2 will be helpful.

**Comment by westonruter** [comment]
As I commented at https://github.com/sabberworm/PHP-CSS-Parser/pull/206#issuecomment-822665064, updating the PHP requirement detrimental for WordPress which still supports PHP 5.6. If PHPDoc can be used until WordPress [increases the minimum](https://make.wordpress.org/core/2020/08/24/proposal-dropping-support-for-old-php-versions-via-a-fixed-schedule/), this would be ideal. Otherwise, the [dozens of WordPress plugins](https://wpdirectory.net/search/01F3NM1ZE9PHFQJ957XEXBJJ7C) that use PHP-CSS-Parser would be forced to fork the package.

**Comment by oliverklee** [comment]
Then I propose we start with raising the minimum required PHP version to 5.6. What do you think?

**Comment by westonruter** [comment]
Yes, that works for me!

**Comment by oliverklee** [comment]
Okay then, 5.6.20 it is (which are the current WordPress PHP requirements). I will create a PR after some of my other PRs are merged.
